### ISSUE TITLE
Twitch login is not working.

### ISSUE THREAD

**Issue by r4ha** [DiegoAce/StreamBlend#2]
https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

**Comment by DiegoAce** [comment]
Thanks for letting me know! I'll have a fix out soon.

**Comment by DiegoAce** [comment]
I submitted update 1.14. It should be available for FireFox and Chrome soon. Once it is, please test and close this issue if it fixes the problems with Twitch.

**Comment by r4ha** [comment]
It works! Thanks for the quick update!
